---
- name: install php via Python Script
  hosts: test
  remote_user: centos
  become: yes

  - name: install php by python
    command: /usr/bin/python /root/php_install.py {{version}}
    dest: /usr/local/src