---
- name: "Playbook to add key to ec2 instances"
  hosts: hosts_to_add_key
  vars:
    - status: "present"
    - key: "~/.ssh/id_rsa.pub"

  tasks:
  - name: "Copy the authorized key file from"
    authorized_key:
      user: "{{ ansible_user }}"
      state: "{{ status }}"
      key: "{{ lookup('file', '{{ key }}')}}"
