---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    region: ap-southeast-1
    key: keypair-jev-prd
    instance_type: t2.micro
    image: ami-07f65177cb990d65b
    prefix: staging
  tasks:
    - name: web instance provisioning
      ec2:
        region: "{{ region }}"
        key_name: "{{ key }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: yes
        group: "sg_jev_prd_ase1_pri_web"
        vpc_subnet_id: "subnet-06eadca353a7458d2"
      register: ec2 