---
- name: Create instances
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    region: ap-southeast-1
    key: keypair-auto-dev-pri

    instance_type: t2.micro
    instance_type_db: t3.small
    
    image: ami-07f65177cb990d65b
    
    web_group: sg_auto_dev_ase1_pri_web
    was_group: sg_auto_dev_ase1_pri_was
    db_group: sg_auto_dev_ase1_pri_db

    web01_vpc_subnet_id: subnet-0ac15e7d84120fb5f
    web02_vpc_subnet_id: subnet-0e8880ca52c258fc2
    was01_vpc_subnet_id: subnet-038c32b93b1bb5748
    was02_vpc_subnet_id: subnet-0042fa4d6caea29f3
    db_vpc_subnet_id: subnet-0a12abea62df584ef
    
    device_name: /dev/sda1
    volume_type: gp2

  tasks:
    - name: web01 server provisioning
      ec2:
        region: "{{ region }}"
        key_name: "{{ key }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: yes
        group: "{{ web_group }}"
        vpc_subnet_id: "{{ web01_vpc_subnet_id }}"
        private_ip: "10.50.20.20"
        instance_tags:
          Name: ec2-auto-dev-ase1-pri-web01G
          Creater: Ansible
        termination_protection: yes
        volumes:
          - volume_size: 30
            device_name: "{{ device_name }}"
            volume_type: "{{ volume_type }}"
      register: ec2
    - name: web02 server provisioning
      ec2:
        region: "{{ region }}"
        key_name: "{{ key }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: yes
        group: "{{ web_group }}"
        vpc_subnet_id: "{{ web02_vpc_subnet_id }}"
        private_ip: "10.50.20.200"
        instance_tags:
          Name: ec2-auto-dev-ase1-pri-web02G
          Creater: Ansible    
        termination_protection: yes   
        volumes:
          - volume_size: 30
            device_name: "{{ device_name }}"
            volume_type: "{{ volume_type }}"
      register: ec2
    - name: was01 server provisioning
      ec2:
        region: "{{ region }}"
        key_name: "{{ key }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: yes
        group: "{{ was_group }}"
        vpc_subnet_id: "{{ was01_vpc_subnet_id }}"
        private_ip: "10.50.30.20"
        instance_tags:
          Name: ec2-auto-dev-ase1-pri-was01G
          Creater: Ansible    
        termination_protection: yes 
        volumes:
          - volume_size: 30
            device_name: "{{ device_name }}"
            volume_type: "{{ volume_type }}"
      register: ec2      
    - name: was02 server provisioning
      ec2:
        region: "{{ region }}"
        key_name: "{{ key }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: yes
        group: "{{ was_group }}"
        vpc_subnet_id: "{{ was02_vpc_subnet_id }}"
        private_ip: "10.50.30.200"
        instance_tags:
          Name: ec2-auto-dev-ase1-pri-was02G
          Creater: Ansible    
        termination_protection: yes  
        volumes:
          - volume_size: 30
            device_name: "{{ device_name }}"
            volume_type: "{{ volume_type }}"
      register: ec2            
    - name: db server provisioning
      ec2:
        region: "{{ region }}"
        key_name: "{{ key }}"
        instance_type: "{{ instance_type_db }}"
        image: "{{ image }}"
        wait: yes
        group: "{{ db_group }}"
        vpc_subnet_id: "{{ db_vpc_subnet_id }}"
        private_ip: "10.50.100.20"
        instance_tags:
          Name: ec2-auto-dev-ase1-pri-dbG
          Creater: Ansible    
        termination_protection: yes        
        volumes:
          - volume_size: 30
            device_name: "{{ device_name }}"
            volume_type: "{{ volume_type }}"
      register: ec2        