---
- name: Install apache to webserver
  hosts: webserver
  remote_user: centos
  become: yes
  tasks:
    - name: Set hostname
      hostname:
        name: {{ invertory_hostname }}

    - name: Copy shell script
      copy:
        src: "{{ item }}"
        dest: /tmp
        mode: 0777
      with_items:
        - apache_install.sh

    - name: Execute shell script
      command: sh /tmp/apache_install.sh "{{ apache_directory }}" "{{ apache_version }}" "{{ apr_version }}" "{{ aprutil_version }}" "{{ pcre_version }}"

    - name: Fetch install log file
      fetch:
        src: /tmp/"{{ invertory_hostname }}"_apacheinstall_log
        dest: /usr/local/apmtauto