---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    region: ap-southeast-1
    key: keypair-auto-dev-pri
    instance_type: t2.micro
    image: ami-07f65177cb990d65b
    web_group: sg_auto_dev_ase1_pri_web
    device_name: /dev/sda1
    volume_type: gp2

  tasks:
    - name: web01 server provisioning
      ec2:
        region: "{{ region }}"
        key_name: "{{ key }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: yes
        group: "{{ web_group }}"
        vpc_subnet_id: "subnet-0ac15e7d84120fb5f"
        private_ip: "10.50.20.15"
        instance_tags:
          Name: ec2-auto-dev-ase1-pri-web01
          Creater: Ansible
        
        user_data: |
          #!/bin/bash
          yum -y install python-pip
          pip install boto

        termination_protection: yes
        volumes:
          - volume_size: 30
            device_name: "{{ device_name }}"
            volume_type: "{{ volume_type }}"
      register: ec2_instances

    - name: Get volumes ids
      ec2_vol:
        region: "{{ region }}"
        instance: "{{ item }}"
        state: list
      with_items: "{{ ec2_instances.instance_ids }}"
      register: ec2_instances_volumes
      loop_control:
        label: "{{ item }}"

    - name: Tag volumes
      ec2_tag:
        region: "{{ region }}"
        resource: "{{ item.1.id }}"
        tags:
          Name: volume-auto-dev-ase1-web01
      with_subelements:
        - "{{ ec2_instances_volumes.results }}"
        - volumes