---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    region: ap-southeast-1
    key: keypair-auto-dev-pri

    instance_type: t2.micro
    instance_type_db: t3.small

    image: ami-07f65177cb990d65b

    web_group: sg_auto_dev_ase1_pri_web
    was_group: sg_auto_dev_ase1_pri_was
    db_group: sg_auto_dev_ase1_pri_db

    device_name: /dev/sda1
    volume_type: gp2
  tasks:
    - name: web01 server provisioning
      ec2:
        region: "{{ region }}"
        key_name: "{{ key }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: yes
        group: "{{ web_group }}"
        vpc_subnet_id: "subnet-0ac15e7d84120fb5f"
        private_ip: "10.50.20.15"
        instance_tags:
          Name: ec2-auto-dev-ase1-pri-web01
          Creater: Ansible
        termination_protection: yes
        volumes:
          - volume_size: 30
            device_name: "{{ device_name }}"
            volume_type: "{{ volume_type }}"
      register: ec2
    - name: web02 server provisioning
      ec2:
        region: "{{ region }}"
        key_name: "{{ key }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: yes
        group: "{{ web_group }}"
        vpc_subnet_id: "subnet-0e8880ca52c258fc2"
        private_ip: "10.50.20.150"
        instance_tags:
          Name: ec2-auto-dev-ase1-pri-web02
          Creater: Ansible
        termination_protection: yes
        volumes:
          - volume_size: 30
            device_name: "{{ device_name }}"
            volume_type: "{{ volume_type }}"
      register: ec2
    - name: was01 server provisioning
      ec2:
        region: "{{ region }}"
        key_name: "{{ key }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: yes
        group: "{{ was_group }}"
        vpc_subnet_id: "subnet-038c32b93b1bb5748"
        private_ip: "10.50.30.15"
        instance_tags:
          Name: ec2-auto-dev-ase1-pri-was01
          Creater: Ansible
        termination_protection: yes
        volumes:
          - volume_size: 30
            device_name: "{{ device_name }}"
            volume_type: "{{ volume_type }}"
      register: ec2
    - name: was02 server provisioning
      ec2:
        region: "{{ region }}"
        key_name: "{{ key }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: yes
        group: "{{ was_group }}"
        vpc_subnet_id: "subnet-0042fa4d6caea29f3"
        private_ip: "10.50.30.150"
        instance_tags:
          Name: ec2-auto-dev-ase1-pri-was02
          Creater: Ansible
        termination_protection: yes
        volumes:
          - volume_size: 30
            device_name: "{{ device_name }}"
            volume_type: "{{ volume_type }}"
      register: ec2
    - name: db server provisioning
      ec2:
        region: "{{ region }}"
        key_name: "{{ key }}"
        instance_type: "{{ instance_type_db }}"
        image: "{{ image }}"
        wait: yes
        group: "{{ db_group }}"
        vpc_subnet_id: "subnet-0a12abea62df584ef"
        private_ip: "10.50.100.15"
        instance_tags:
          Name: ec2-auto-dev-ase1-pri-db
          Creater: Ansible
        termination_protection: yes
        volumes:
          - volume_size: 30
            device_name: "{{ device_name }}"
            volume_type: "{{ volume_type }}"
      register: ec2
