---
- name : Install Tomcat on CentOS
  hosts: was02
  gather_facts: no
  remote_user: centos
  become: yes

  tasks:
  - name: Copy python script
    copy:
      src: tomcat_install.py
      dest: /usr/local/src
      mode: 0700

  - name: Execute python script
    shell: python ./httpd_install.py "{{ TOMCAT_VERSION }}"
    args:
      chdir: /usr/local/src