---
- name : Install Apache on CentOS
  hosts: cent
  gather_facts: no
  remote_user: centos
  become: yes

  tasks:
  - name: Installing Latest version of Apache
    yum: name=httpd state=latest
  - name: (Enable it on System Boot)
    service: name=httpd enabled=yes
    notify:
      - start apache
  handlers:
    - name: start apache
      service: name=httpd state=started